version: "3.9"

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dental_sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -lc 'echo > /dev/tcp/127.0.0.1/1433'"]
      interval: 5s
      timeout: 5s
      retries: 12

  api:
    build:
      context: .
      dockerfile: src/DentalClinic.Api/Dockerfile
    depends_on:
      sql:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:8080"
      ConnectionStrings__Default: "Server=sql,1433;User ID=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Database=DentalClinic"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"
